travis:
  secure:
    BINSTAR_TOKEN: OdyLtS2JaBbiGa+0OuiIElfLNBOUzEYnFVn5HhVoGMLIdgaRklJ69rYDLR8nZegxgTULl+/EArPcOTbRxejwLMdw4QJVcTP5+0Ekv2n2GIechWRRj2fWoxXP+52SrLaJIE4h6DWfnQDmYL3z2tD+EXRA3JBppvQq1XL0EiTausD2kvRoeg7RRpWjK149z4HvPj5Ok2qIBSRLuUCiD3HfKH1N/2wJhv5gmB8bJLx71Hoi4OxXY1suPYgArwoIeA5+UG9lBwC5hOIK5VT9OjOPYv+qW7X6Oy4JMVsuMqTqx+7uSI45FwZ4lGSmE9ar9rJ/fKS5i3eHh41wWvf9eJNgVXjJHbDPeyQdn8B0gxEzC59BEiDaJBvVSkgW8ztM/CBP67ChF6AwGUcr5xMfWDi/3X3RzcjClZZDnYr2dvHcCMAcQBeftfpEIwafOlWDavgg/i3+DfHsqyYJ5pZ4mdZFm/KIrHZAr8ukKZytj8c2nAPsrYhEZ/uorl/SaJi4G/CRANLh+BYWgH3r7VjL2GTSyndMcKyQ6fgly6EvtB1qZ3zgSKhueIsVT3CrmErH4us357c5aXQYVxHA83OCaGmHulpJOQ/4DE401JDiZXQ6j/Q3mWYq28M1s0R3s/clMNxfepf3C6YUN4HtjiQ2Tn2vbKbNxj+W9yHRHZjRHxLQZ2k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
